### ISSUE TITLE
Possible issue in IMQ implementation: continued

### ISSUE THREAD

**Issue by tolstikhin** [schelotto/Wasserstein-AutoEncoders#5]
Hey,

well, I think there is still a bug. Looking at [these lines](https://github.com/schelotto/Wasserstein_Autoencoders/blob/301cc64dd158cc76d066d36c34cbc6d6a5fa6d43/wae_mmd.py#L125-L128), I see:
` p2_norm_x = X.pow(2).sum(1).unsqueeze(0)
    norms_x = X.sum(1).unsqueeze(0)
    prods_x = torch.mm(norms_x, norms_x.t())
    dists_x = p2_norm_x + p2_norm_x.t() - 2 * prods_x`
Why do you sum the coordinates of samples from Pz and Qz before multiplying them?
You want the matrix dists_x to store a squared Euclidean distance between i-th and j-th rows
of the X matrix in the (i,j)-th position. ||x - y||^2 = ||x||^2 + ||y||^2 - 2 * <x, y>.
So prods_x should store pair-wise inner products between the rows of X. 
If I'm not mistaken, right now prods_x stores something else.... Correct me if I'm wrong.

Best wishes,
Ilya

**Comment by ethancaballero** [comment]
@schelotto Any updates?

**Comment by schelotto** [comment]
@tolstikhin @ethancaballero I will take a look at it 2 weeks later. stay tuned.

**Comment by jnhoward** [comment]
Hi,

Yes, I think there is an issue as well. I think simply changing it to prods_x = torch.mm(norms_x.(t), norms_x) would give the right behavior. And then analogously for prods_y and dot_prd. Namely, prods_y = torch.mm(norms_y.(t), norms_y) and dot_prd = torch.mm(norms_y.t(), norms_x).

Best,
Jessica

**Comment by alooow** [comment]
Hi, 

Both `prods_x = torch.mm(norms_x, norms_x.t())` and  `prods_x = torch.mm(norms_x.t(), norms_x.)` are incorrect. Please note that if `X` is _batch_size_ x _D_ matrix then `X.sum(1)` is a _batch_size_-dimensional vector, so `norms_x = X.sum(1).unsqueeze(0)` has size (_1_, _batch_size_) and at i-th position stores the sum of all elements of the i-th vector in X (norm_x_i = sum_{k} X_i,k ). 

So now doing  `prods_x = torch.mm(norms_x, norms_x.t())` simply returns a scalar (since we are multiplying matrices (1, _batch_size_), (_batch_size_,1)), which is the sum of squared sums of vectors of X (i.e the `prods_x` = sum_{t}(sum_{k} `X`_t,k)^2).  This is obviously wrong, since, as mentioned above, `prods_x` should be a (_batch_size_, _batch_size_) matrix,  where prods_x_i,j is equal to <X_i,X_j>. 

On the other hand, `prods_x = torch.mm(norms_x.t(), norms_x)` does return a (_batch_size_, _batch_size_) matrix, but with wrong values.  Now prods_x_i,j  is equal to the multiplication of sums of vectors X_i and X_j:  (i.e. prods_x_i,j = (sum_{k} X_i,k)(sum_{l} X_j,l)) = sum_{k}{l} X_i,k X_j,l). This is again wrong, as we want to multiply and sum X_i,k X_j,l only when k == l. (Because <X_i, X_j> = sum_{k} X_i,k, X_j,k). 

So I guess if one wants the correct `prods_x` matrix the simplest way is:
`prods_x = torch.mm(X, X.t())`. The `norms_x = X.sum(1).unsqueeze(0)` are completely unnecessary and misleading. 

So to conclude the computation of `dists_x` (and other distances as well), should look like this:
```
  norm_x = X.pow(2).sum(1).view(-1,1) # batch_size x 1    
  prods_x = torch.mm(X, X.t()) # batch_size x batch_size    
  dists_x = norm_x + norm_x.t() - 2*prods_x
```
The same with unsqueeze(0)  is also fine. That said, I think they might still be some issues with the mmd penalty (mentioned in #6).

Sorry for the equations - I hope I did not make a mistake in them. I just thought it would be helpful to explain what is going on. Also let me know if I made an error somewhere, 

Best,
Alex

**Comment by A-Rain** [comment]
@jnhoward  @alooow @tolstikhin Hi there, first alooow‘s code is correct, I have used some toy examples to validate it. Secondly, Why can we use some some more simple codes  for ||x - y||^2

```python
import torch

# B is batch size and H is hidden size
B, H = 8, 5
z = torch.randn(B, H)

# this part is  alooow's modified code
norm_x = z.pow(2).sum(1).view(-1,1) # batch_size x 1    
prods_x = torch.mm(z, z.t()) # batch_size x batch_size    
dists_x = norm_x + norm_x.t() - 2*prods_x 

dists_x_sum = dists_x.sum().sum()

# this is my modified code
temp = z.expand(B, B, H)
temp = c - c.transpose(0,1)
res = temp.pow(2).sum(2).squeeze() # batch_size x batch_size
res_sum = res.sum().sum()

# this part is the code using loop to validate the final result
ground_truth = 0
for i in range(B):
    for j in range(B):
        ground_truth += (z[i]-z[j]).pow(2).sum()
```

we could find that ```dists_x_sum``` and ```res_sum``` equals ```ground_truth```. Besides matrix ```res``` and ```dists_x``` are the same.

But I don't understand this part of the source code:
![ques](https://user-images.githubusercontent.com/29532760/73645515-691f3f80-46b2-11ea-9cdd-58cb67dd666f.png)

why using several scales? can we just use one specific scale?

**Comment by AustinT** [comment]
Thank you guys for this thread: it's annoying that a repo implementing a popular paper in pytorch with so many stars has a completely incorrect MMD function! I addressed this issue in my PR #10

**Comment by kalinlau** [comment]
THX @AustinT. Would u mind close this issue considering it solved?@schelotto

**Comment by DaehanKim** [comment]
@A-Rain I was curious on the same part. I guess it's a kind of kernel ensemble though its a bit different from the original paper description(```2 d_h \sigma_z^2```) Plus I think MMD approximation with batch size `n` should be `dists_x` divided by `n(n-1)` (analogous for `dists_y`) and `dists_c` divided by `n**2`. But this Implementation only divides with `n-1` and `n` respectively. Why is it so?
